import type { Metadata } from "next";

// ------------- Components ------------- \\
import DashboardDisplay from "./_components/display";
import Modal from "@/components/modal";

// ------------- Hooks ------------- \\
import { useServerSession } from "@/hooks/useServerSession";

// ------------- Contexts ------------- \\
import { ChatProvider } from "@/context/chatContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await useServerSession();

  const modals = [
    {
      id: "rm-chat",
      title: "delete chat?",
      context: "This will delete Junior React Developer Application.",
    },
    {
      id: "rm-account",
      title: "remove account?",
      context: "this will remove your account",
    },
  ];

  return (
    <body className="h-full w-full bg-[#212121] text-white flex items-start justify-center">
      <Modal modals={modals} />
      <DashboardDisplay>
        <ChatProvider userId={user.id}>{children}</ChatProvider>
      </DashboardDisplay>
    </body>
  );
}
