import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

// --------- Context ------------- \\
import { ErrorProvider } from "@/context/errorContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ErrorProvider>
      <html lang="en" className="h-full">
        {children}
      </html>
    </ErrorProvider>
  );
}
